### ISSUE TITLE
A minimal storage market

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-codex#14]
- TODO

**Comment by Menduist** [comment]
I've been thinking about the storage market, and I think it may not be a good idea to lock up funds to be able to bid.

We aim to have a global market, and who says global market says a lot of competition.
It means that on a given contract, we should have tens, if not hundreds of bids, and only a fraction of them will be accepted.

For instance, let's say on average, 10% of bids are accepted (it seems a lot, but anyway)
It means that as a storage node, I have, on average, to place 10 bids to win one contract.

If I have to lock up funds for each of theses bids, it means that not only I'll have a lot of funds locked up, but also I'll have to pay a lot of fees (to lock up theses funds), without being sure of having any contracts in the end.


But this property also allows us to reduce the probability of "double bidding" (like double spending):
Since I have "low" (10%) probability of actually getting a contract, the probability that I get two contracts is even lower (1%), especially if we have a fast marketplace with bids with little TTL.
(Obviously, in reality, the probability of getting a bid are not random, but depends on you're price, but simplifying here)

My idea would be:
- I want a contract with 5 storage nodes
- I create and send that contract
- Get 50 bids
- Choose the 10 best
- Lock up my funds, send the contract + 10 bids to the blockchain
- The 5 first to lock up their fund win the contract

In reality we could probably have less than 50% of "backup bids".
And if I'm very unlucky and end up with less than 5 storage node?
I can recreate a contract, which is not ideal, but should not happen in regular operation
