### ISSUE TITLE
Remove hard requirement of reachable Ethereum provider

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-codex#163]
Owing to recent changes on `main`, when following the instructions in the Codex readme and running e.g. `./build/codex --data-dir="$(pwd)/Codex1" -i=127.0.0.1` the process crashes almost immediately if the default `--eth-provider` is not reachable.

It seems there's presently a hard requirement that an Ethereum RPC endpoint is reachable, the default endpoint being `ws://localhost:8545`.

The availability of an Ethereum provider should be opt-in.

**Comment by markspanbroek** [comment]
That's not good, indeed. It should be opt-in. Thanks for reporting, I'll have look.

**Comment by markspanbroek** [comment]
The behavior at the moment is: if there's a `vendor/dagger-contracts/deployment.json` present then the node tries to contact the Ethereum node. If you ever did an `npm start` in `vendor/dagger-contracts` then that file is present, and in subsequent runs of the node it will try to contact the Ethereum node. If you remove that file, it should no longer try to reach the Ethereum node.

This is probably not very intuitive, so I'm thinking of changing the behavior as follows:
- If there's an `--eth-account` specified, then it will try to read `deployment.json` and contact the Ethereum node. It will crash when either is missing.
- If there's no `--eth-account` specified, then no attempt will be made to read `deployment.json`, nor to contact the Ethereum node.

This has the added benefit of not being able to accidentally use the default account in the Ethereum node, because an Ethereum account has to always be specified explicitly.

**Comment by dryajov** [comment]
We should add an explicit flag that enables and disables the payment and durability machinery and I would leave it off by default, at least for now. If the user specifically enables it and we're missing configurations or unable to reach the endpoint, we should print intuitive messages so that the user isn't stumped by the behavior.

In other words, the durability piece is optional, even if it's central to what we're doing. There are many more uses where durability isn't needed to interact with the network, for example retrieving/consuming data. Even with bandwidth payments, the user might choose to only interact with altruistic nodes, in which case operating without a payments backend is totally fine.
