### ISSUE TITLE
getBlock: return BlockNotFound exception

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [status-im/nim-codex#210]
Modify #205 in the following way:
- add exception BlockNotFound as subtype of CodexError
- return it from getBlock when appropriate
- modify places where getBlock is called, to distinguish BlockNotFound from other errors - only when it makes sense. When you are in doubt, we may discuss concrete places

Note - all other exceptions should be processed in the same way as in #205 or prior to it. We just want to modify BlockNotFound handling, so it combines the benefits of #205 and prior code.

**Comment by michaelsbradleyjr** [comment]
Leaving some notes per our discussion earlier today.

On the [alt_alt_182](https://github.com/status-im/nim-codex/compare/182_update_getBlock_return...alt_alt_182) branch off  #205's branch, I made some changes to demonstrate the problem of trying to return a subtype of `CodexError`, which is a subtype of `CatchableError`.

You *can* return `ref BlockNotFoundError`, but it's not possible for the caller to distinguish the types, or at least I was unable to figure out a way to do that.

For that reason, I took the approach in #209.

I propose we close #209 and proceed with #205, or close #205 also and stick with `?!(?Block)` as currently used in `main`.

**Comment by michaelsbradleyjr** [comment]
It turned out that `if..of` provides the desired behavior.

In the changes I made on [`alt_alt_182`](https://github.com/status-im/nim-codex/compare/182_update_getBlock_return...alt_alt_182) you can see if the `when..is` and `if..is` aren't viable for this purpose, and `case..of` results in compilation errors. But `if..of` works exactly like we want!

PR #219 is the result of reworking PR #209 to use `if..of`.
