### ISSUE TITLE
Support latest version of nim-ethers

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-codex#220]
The latest version of nim-ethers depends on `nim-eth`, which was recently removed from `nim-codex`. Need to consider an alternative crypto for `nim-ethers` or add back the dependency of `nim-eth` to `nim-codex`.

**Comment by arnetheduck** [comment]
The option that would benefit status as a whole would be to unify nim-ethers with nim-web3, or simply use nim-web3 in codex as well, as happens for all other projects that need to access the web3 interfaces - this will make it easier down the line to integrate codex with waku and other infrastructure-level software.

Having two libraries that do the same thing with slightly different syntax means we have a lot of maintenance and bugfixing overhead that is unnecessary and inefficient - this overhead will only grow over time the more codex diverges from the other projects in trivial aspects like web3-vs-ethers which really aren't core features of codex: if web3 replaced ethers, it would only have minimal and isolated effect on codex as a whole, but would benefit both codex and other infra projects because maintenance would be shared.

Removing the dependency on nim-eth in ethers would mean _even  more_ duplication of work because it would now have to solve the problems that nim-eth already has solved - the costs go above and beyond simply duplicating the functionality with different code: we have to test, maintain, document and above all audit two codebases, which is a significant cost that is not easily seen at the start of the journey.

**Comment by dryajov** [comment]
> The latest version of nim-ethers depends on `nim-eth`, which was recently removed from `nim-codex`. Need to consider an alternative crypto for `nim-ethers` or add back the dependency of `nim-eth` to `nim-codex`.

The easiest alternative is to add back `nim-eth`, lets do that please.

**Comment by emizzle** [comment]
@arnetheduck I believe the reason that `nim-ethers` diverged from `nim-web3` was that `nim-web3` uses an abi decoder library that was limited in functionality or did not fit our needs, and there was friction/delay in getting work approved to improve it. I'm certainly not disagreeing with you, merely shedding some light on the "why".

**Comment by emizzle** [comment]
Closed via https://github.com/status-im/nim-codex/pull/236
