### ISSUE TITLE
Persist availability on disk

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-codex#296]

**Comment by emizzle** [comment]
@markspanbroek, I've been working on getting this working. Right now, we have a REST endpoint that creates Availability, that upon storage request completion, could continually be reused in future storage requests. What do you think about creating a setting, `Availability.reusable` that determines if the Availability should be released upon contract completion (ie when `not reusable`), that is set on `Availability` creation from the REST endpoint? This would allow the user to say, for example, "I only want this availability to be used once".

**Comment by emizzle** [comment]
Latest code here (completely WIP): https://github.com/status-im/nim-codex/tree/sales-state/persist-availability

**Comment by markspanbroek** [comment]
Great, thanks for starting the work on this @emizzle! I expect that we'd like to change the REST API quite significantly later on. We'll most likely end up with an API where the user tells the node how much space they want to rent out in total (for all contracts combined), and for how long they'd like to guarantee node uptime (so that no contracts are accepted that exceed that timeframe). The node should then figure out which contracts fill most of the space most of the time.

But that seems like a much bigger task then persistence of availability, so feel free to take the availability API as it is right now, and persist that. We can then plan the move to a new API as a subsequent task.

**Comment by emizzle** [comment]
Thank Mark. I think maybe it would be less redundant work if we held off on doing this work until we've updated the marketplace REST api.

**Comment by markspanbroek** [comment]
Yes, it would be less redundant, but it would also delay user testing. I'd rather have some form of persistence for our test users.

**Comment by dryajov** [comment]
Just FYI, the `repostore.nim` already has a `reserve/release` (https://github.com/status-im/nim-codex/blob/main/codex/stores/repostore.nim#L243-L290) method to enable this behavior at the repo level.
